name: Setup
description: 'Setup JS workflow, install dependencies and cache them'
author: 'chillios-dev'

runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install packages
      shell: bash
      run: bun install
