name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        If this is not a bug report, please use other relevant channels:

        Before you proceed:

        - Make sure you are on latest versions of SwapDK packages.

  - type: textarea
    attributes:
      label: Current behavior
      description: |
        What code are you running and what is happening? Include a screenshot or video if it's an UI related issue.
      placeholder: Current behavior
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        What do you expect to happen instead?
      placeholder: Expected behavior
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Functionality
      description: |
        What functionality is affected by the issue?
      options:
        - label: Api
        - label: Liquidity
        - label: Other
        - label: Swap
        - label: Transactions
        - label: Wallet

  - type: checkboxes
    attributes:
      label: Packages
      description: |
        Which packages are affected by the issue?
      options:
        - label: "@swapdk/core"
        - label: "@swapdk/helpers"
        - label: "@swapdk/plugins"
        - label: "@swapdk/sdk"
        - label: "@swapdk/toolboxes"
        - label: "@swapdk/ui"
        - label: "@swapdk/wallets"

  - type: textarea
    attributes:
      label: Details
      description: |
        Please provide additional details, if any like screenshots, videos, error stack traces, package versions, etc.
      value: |
        Package versions:
        ```bash
        # Paste the output of `<npm|yarn|pnpm|bun pm> ls --depth=0 | grep @swapdk` here
        ```
    validations:
      required: true
